# docker-compose.yml
version: "3.2"

services:
  nginx:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./site01/html:/usr/share/nginx/html/site01.com
      - ./site02/html:/usr/share/nginx/html/site02.com
